### ISSUE TITLE
Anything that is compatible with SIE and BAS?

### ISSUE THREAD

**Issue by zenny** [plaintextaccounting/plaintextaccounting#102]
Hi,

I am searching for a plain text accounting that complies with the Swedish BAS (https://bas.se/en) and outputs to SIE (https://sie.se/en)?

I came across an isolate on SIE part (https://github.com/kjelloh/SIEParsePlayGround and https://github.com/byrokrat/accounting). 

Has anyone any idea if anyone has worked on the same for either @jwiegley's  ledger (https://github.com/ledger/ledger) or @simonmichael's hledger (https://github.com/simonmichael/hledger) or @blais' https://github.com/beancount/beancount?

Your input appreciated! Cheers, /z

**Comment by simonmichael** [comment]
Closing; you could try reddit.com/r/plaintextaccounting
