### ISSUE TITLE
Possibly include `coin` in the list of PTA implementations

### ISSUE THREAD

**Issue by mkobetic** [plaintextaccounting/plaintextaccounting#130]
I'm not sure what the criteria for inclusion are so feel free to reject, but I have been working on https://github.com/mkobetic/coin (time permitting) and using it for personal finances since probably 2015. I only published it to GitHub in 2019 when I thought it wouldn't be too embarrassing. I certainly wouldn't promote it in favour of the big ones, but it's usable and it works for me. I'm not aware of any other users but myself so far.

I'm not sure that this is much of a contribution, but I find the PTA idea brilliant and am grateful to its inventors and supporters. I'm still having fun playing with coin. ❤️

**Comment by simonmichael** [comment]
We include all PTA-related apps - I have added yours, thanks.

I like your simplifications!

**Comment by mkobetic** [comment]
Thank you, Simon! The Code column seems to be for the implementation language, so for `coin` it should probably be `go`, although `mynt` below is also listed as `mynt`, looks like that one is in `rust`.

**Comment by simonmichael** [comment]
Oops, thank you, I have pushed a fix.
