### ISSUE TITLE
wish: a bot that updates html when needed

### ISSUE THREAD

**Issue by simonmichael** [plaintextaccounting/plaintextaccounting#18]
We generate/commit/push HTML ourselves rather than depending on jekyll. This allows the use of pandoc or other tools and I'd like to continue that. But it's tedious and unintuitive having to remember this (eg #17). It would be nice if Someone (eg me) ran a bot that watches the repo for commits changing source files but not HTML, and pushes a HTML update in that case. This would mean all we need to do is push markdown updates. The history may get more cluttered with separate HTML commits though.

**Comment by alexjj** [comment]
I [still suggest setting up Netlify](https://github.com/plaintextaccounting/plaintextaccounting.github.io/issues/6#issuecomment-251484064) to build the site for you - still using pandoc.

**Comment by tbm** [comment]
> I still suggest setting up Netlify to build the site for you - still using pandoc.

Agreed. @simonmichael you had some concerns about complexity (SSL, CDN, etc) but of all that is handled for you by Netlify.  You basically get it for free (in fact, you do get it for free ;)

**Comment by simonmichael** [comment]
If I wanted to have co-maintainers at the site admin level, to reduce bus factor, I think that's free with the current setup, but would cost $45/mo with Netlify. I haven't tried it yet. But I hear you.

**Comment by alexjj** [comment]
Not to sound like a broken record but...Netlify is free 😉 Have the multiple owners/maintainers at Github level. If you're worried about a bus you'll still need to give domain DNS control... If multiple people have github access then they can setup their own Netlify instance to host it and aside from DNS it would be up and running and working perfectly fine.

**Comment by simonmichael** [comment]
If it ain't broke, I'm not too motivated to add complexity to my workload.

But there's no reason y'all couldn't experiment with these things, eg as mirrors, and see/show us how it works out.

**Comment by simonmichael** [comment]
Resolved - the site is now built by Cloudflare Pages, and we no longer need to commit HTML.
