### ISSUE TITLE
Effective Dates

### ISSUE THREAD

**Issue by alensiljak** [plaintextaccounting/plaintextaccounting#65]
Hi!
Do you think adding Effective Dates syntax to [quickref](https://plaintextaccounting.org/quickref/) would be useful?

These are quite handy for a couple of scenarios so perhaps worth a mention.

[Reference](https://www.ledger-cli.org/3.0/doc/ledger3.html#Effective-Dates)

**Comment by colindean** [comment]
I think it'd be valuable. I know I use them but they have some logical rough edges. Do they behave sufficiently similarly on all ledger-likes?

**Comment by simonmichael** [comment]
Even if not, I think they’d be a fine addition - detailing supported syntax and any differences is the doc’s purpose after all.

**Comment by MisterY** [comment]
Great!
From what I see, Beancount's implementation is still at the level of a [proposal](http://furius.ca/beancount/doc/proposal-settlement) although I can't confirm that yet.
[Ledger's implementation](https://www.ledger-cli.org/3.0/doc/ledger3.html#Effective-Dates) is implemented and, so far, I can confirm the following syntax works:

```
2019-01-30=2019-01-15 Effective Transaction
	Assets:Cash    2 EUR
	Income:Tax Refun    -2 EUR

;This doesn't work
;2019-02-10 [=2019-01-15] Different Syntax
;	Assets:Cash    2 EUR
;	Income:Tax Refun    -2 EUR

2019-02-10 Comments Syntax
	; [=2019-01-15]
	Assets:Cash    2 EUR
	Income:Tax Refun    -2 EUR

2019-03-01 Separate Ways
	Assets:Cash    2 EUR
	Income:Tax Refun    -2 EUR ; [=2019-01-15]
```

**Comment by tbm** [comment]
> ;2019-02-10 [=2019-01-15] Different Syntax

I can confirm that this is not valid.

I can also confirm that beancount currently doesn't have effective dates.

It might be worth mentioning that they are called "secondary date" or date2 in hledger.

**Comment by simonmichael** [comment]
Would anyone like to try adding this to the quickref ? The source file is https://github.com/plaintextaccounting/plaintextaccounting.github.io/blob/master/quickref/index.html . If not, I'll close this.

**Comment by simonmichael** [comment]
Closing.
