### ISSUE TITLE
move quick reference into main site

### ISSUE THREAD

**Issue by simonmichael** [plaintextaccounting/plaintextaccounting#9]
http://plaintextaccounting.org/quickref/ was prototyped with google docs, and is exported from there. This is not ideal for maintenance and contribution, I'd like to have it in the main repo instead, as markdown, html, or whatever, hopefully still with a useful layout and not too painful to edit.

**Comment by simonmichael** [comment]
Latest thinking: convert to a markdown skeleton doc with standard headings. Fill out a copy of this for each ledgerlike. Optionally combine these to render a pretty tabular combined doc. Maybe some day move these to each project's repo. See mockups in https://github.com/plaintextaccounting/plaintextaccounting.github.io/tree/master/quickref.

**Comment by tbm** [comment]
Hey @simonmichael there are some issue with the info on beancount.  Unfortunately I'm not sure how to update the current file(s).

Can you finish this ticket so I can send fixes.

**Comment by simonmichael** [comment]
@tbm I'd like to do more, but for now can you edit the HTML file directly ? I believe that's what I've been doing for a while. We should drop the google doc link.

**Comment by simonmichael** [comment]
Closing.
